### ISSUE TITLE
backup tool does not work in azure enviroment

### ISSUE THREAD

**Issue by thej4ck** [tatewake/dokuwiki-plugin-backup#41]
i've 2 installation on azure, as services app.
No particular plugins, only AuthRemoteUser plugin to easely autenticate using AAD backend.
If i launch backup i get this:
![image](https://user-images.githubusercontent.com/5577620/91698568-3a4b4800-eb73-11ea-9ec4-5ccb96e6fe78.png)

I have this beahaving on both installations.

A part of this plugin, all is working correctly.

i thing that all is related on how azure manage file permissions.

ps. i use IIS with php 7.2.

**Comment by tatewake** [comment]
Hi @thej4ck ,

If my memory is correct, `tpl` is a directory where DokuWiki templates live.

Try running the backup without including "templates".

If the backup succeeds then possibly the `tpl` directory has too restrictive permissions, and making the permissions less strict should resolve this issue.

**Comment by thej4ck** [comment]
that does not resolve. i get an error on the next directory. I've a third installation on azure without AuthRemoteUser plugin. Does this auth plugin affect in some way the backup process?

**Comment by tatewake** [comment]
Hi @thej4ck ,

You need to ensure that the directories you're trying to back up are accessible by the plugins.

This is a configuration issue within your server and how directory permissions are set, and not a problem with the plugin or DokuWiki.

**Comment by thej4ck** [comment]
i'm issuing this because i think is not related on directory permission. it's a standard installation on azure with AuthRemoteUser plugin. No problem for me, i can backup with other tools.
